const LogActivityAction = Object.freeze({
  ADD_LIVESTOCK: "ADD_LIVESTOCK",
  UPDATE_LIVESTOCK: "UPDATE_LIVESTOCK",
  CHANGE_PHASE: "CHANGE_PHASE",
  ADD_LACTATION: "ADD_LACTATION",
  UPDATE_LACTATION: "UPDATE_LACTATION",
  DELETE_LIVESTOCK: "DELETE_LIVESTOCK",
  ADD_MILKPRODUCTION: "ADD_MILKPRODUCTION",
  DELETE_MILKPRODUCTION: "DELETE_MILKPRODUCTION",
  ADD_BODYMASS: "ADD_BODYMASS",
  DELETE_BODYMASS: "DELETE_BODYMASS",
});

module.exports = LogActivityAction;
